### ISSUE TITLE
(Windows) impossible to unzip the file

### ISSUE THREAD

**Issue by un-pogaz** [Zythom/french-wikipedia-word-list#2]
Je suis sous Windows et je n'ai accès qu'à 7zip qui ne reconnaît pas les archives GZ fractionné comme celle-ci (gz-part00, gz-part01)
Une version TAR.GZ fractionné fonctionnerait.

(J'ai un binaire gzip si vous avez une commande)

**Comment by Zythom** [comment]
Bonjour, je pense qu'un
copy /b wikipedia.fr.txt.gz-part00 + wikipedia.fr.txt.gz-part01 + wikipedia.fr.txt.gz-part02 + wikipedia.fr.txt.gz-part03 + wikipedia.fr.txt.gz-part04 + wikipedia.fr.txt.gz-part05 wikipedia.fr.txt.gz
doit répondre à votre problème.

**Comment by un-pogaz** [comment]
Ok, merci
(Note pour moi: `copy /b [file]+[file]+... [outputfile]` permet de concaténer des fichiers, pratique)
